# Generated by Django 5.0.3 on 2024-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArthurApp', '0006_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('telefone', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
    ]
