# Generated by Django 5.0.3 on 2024-03-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArthurApp', '0007_fornecedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='Fornecedores',
        ),
    ]
