# Generated by Django 5.0.3 on 2024-03-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArthurApp', '0008_rename_fornecedor_fornecedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
    ]
