# Generated by Django 5.0.3 on 2024-03-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArthurApp', '0010_alter_fornecedor_cidade_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ManyToManyField(to='ArthurApp.fornecedor'),
        ),
    ]
