# Generated by Django 5.0.3 on 2024-03-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArthurApp', '0011_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='lancamento',
            field=models.BooleanField(verbose_name='Lançamento'),
        ),
    ]
